[buildPlans.iosevka-chad]
family = "Iosevka Chad"
spacing = "normal"
serifs = "slab"
no-cv-ss = false

[buildPlans.iosevka-chad.variants.design]
capital-a = "curly-base-serifed"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "bilateral-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "serifed"
capital-g = "toothed-serifed-capped"
capital-i = "serifed"
capital-j = "descending-serifed-both-sides"
capital-k = "symmetric-connected-serifed"
capital-m = "slanted-sides-flat-bottom"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "standing-open"
capital-s = "bilateral-serifed"
capital-w = "straight-flat-top"
capital-x = "curly-serifed"
capital-z = "cursive"
i = "serifed-asymmetric"
j = "serifed"
k = "curly-top-left-and-bottom-right-serifed"
l = "serifed-flat-tailed"
m = "short-leg-top-left-and-bottom-right-serifed"
n = "tailed"
q = "diagonal-tailed"
r = "top-serifed"
t = "diagonal-tailed"
w = "straight-flat-top-motion-serifed"
y = "straight"
z = "cursive"
zero = "long-dotted"
one = "base-flat-top-serif"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "straight-crossbar-serifed"
eight = "crossing-asymmetric"
nine = "straight-bar"
tilde = "high"
asterisk = "flip-penta-high"
caret = "high"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold-tall"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash-also-connected"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner"
punctuation-dot = "round"

  [buildPlans.iosevka-chad.ligations]
  inherits = "dlig"